
stages:
  - build
  - deploy


variables:
  IMAGE_NAME: redi
  CONTAINER_NAME: redi-container

build:
  stage: build
  tags:
    - benefit-web-server
  image: maven:3.6.3-jdk-11
  script:
    - docker build -t $IMAGE_NAME .

deploy:
  stage: deploy
  tags:
    - benefit-web-server
  image: docker:19.03.12
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d --name $CONTAINER_NAME -p 8080:8080 $IMAGE_NAME


