
stages:
  - build
  - deploy


variables:
  IMAGE_NAME: redi
  CONTAINER_NAME: redi-container

build:
  stage: build
  tags:
    - benefit-web-server
  image: maven:3.6.3-jdk-11
  script:
    - sudo docker build -t $IMAGE_NAME .
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  tags:
    - benefit-web-server
  image: docker:19.03.12
  script:
    - sudo docker stop $CONTAINER_NAME || true
    - sudo docker rm $CONTAINER_NAME || true
    - sudo docker run -d --name $CONTAINER_NAME -p 8080:8080 $IMAGE_NAME


