
spring.data.mongodb.uri=mongodb://mongo_user:rcw6gxn0xnd-AMU7fkt@37.27.41.7:27017/Redi
server.servlet.context-path=/api

jwt.secret=3KV7Mh6yQ3kEEf9ej9C4kJScAvsUpLwg


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


bucket.name=test
AWS_ACCESS_KEY_ID=AKIARMOIX5R5NV3BTP4E

email.gmail.user=s.batanin@redi.partners
email.gmail.password=nourquptouzqmmhg
AWS_SECRET_ACCESS_KEY=5ZOGW4a4LcieadereHEr60VmRNkEuxrT4ibZCyHT



