
spring.data.mongodb.uri=mongodb://mongo_user:rcw6gxn0xnd-AMU7fkt@37.27.41.7:27017/Redi
server.servlet.context-path=/api

jwt.secret=3KV7Mh6yQ3kEEf9ej9C4kJScAvsUpLwg


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


bucket.name=benefit-media

minio.access.key=benefit-user

email.gmail.user=s.batanin@redi.partners
email.gmail.password=nourquptouzqmmhg
minio.secret.key=9@fvuUh63UL3N^2
minio.endpoint=https://minio-storage.getship.today:9000



