
spring.data.mongodb.uri=mongodb://doadmin:vqJTGL3cmPKp@37.27.41.7:27017/Redi?authSource=admin
server.servlet.context-path=/api/v1
server.port=8086
jwt.secret=3KV7Mh6yQ3kEEf9ej9C4kJScAvsUpLwg


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


bucket.name=benefit-media

minio.access.key=benefit-user

email.gmail.user=s.batanin@redi.partners
email.gmail.password=nourquptouzqmmhg
minio.secret.key=9@fvuUh63UL3N^2
minio.endpoint=https://minio-storage.getship.today:9000



